package bjad.db;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Interface allowing callers to create lists
 * of objects based on the result set created
 * by the database wrapper.
 *
 * @author 
 *    Ben Dougall
 * @param <T> 
 *    The object type generated by the implementation
 *    of the interface.
 */
public interface ResultSetMapper<T>
{
   /**
    * Allows the implementing method to process 
    * a result set row and map the data into 
    * the object which will be added to the 
    * list returned by the database wrapper. 
    * 
    * <br><br>
    * <i>Note: you should only be using the result
    * set's getXXX(x) methods to get data, as the database 
    * job will increment the result set row by row. </i>
    * 
    * @param rs
    *    The result set object containing the row's data.
    * 
    * @return 
    *    Constructed object to add to the list of objects 
    *    returned by the database wrapper
    *    
    * @throws SQLException
    *    Any exceptions will be thrown.
    */
   public T processRow(ResultSet rs) throws SQLException;
}
